server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ["http://localhost:3000","http://localhost:3001" ,"http://localhost:3002" , "http://192.168.137.147:3000", "http://192.168.43.178:3000"]
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: user-management
          uri: lb://USER-MANAGEMENT
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AuthenticationFilter
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
