server:
  port: 8087
spring:
  application:
    name: department-management
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/department
    username: ahadi
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
